export enum DangerTypeInterface {
    CHEMICAL_FACTORS = 'CHEMICAL_FACTORS',
    BIOLOGICAL_FACTORS = 'BIOLOGICAL_FACTORS',
    MECHANICAL_FACTORS = 'MECHANICAL_FACTORS',
    ELECTRICAL_FACTORS = 'ELECTRICAL_FACTORS',
    HUMAN_FACTORS = 'HUMAN_FACTORS',
    ERGONOMIC_FACTORS = 'ERGONOMIC_FACTORS',
    ORGANIZATIONAL_FACTORS = 'ORGANIZATIONAL_FACTORS',
    OTHER_FACTORS = 'OTHER_FACTORS',
}
