export enum FactorsWorkplaceSafetyInterface {
    QUALITY_OF_WORK_EQUIPMENT = 'QUALITY_OF_WORK_EQUIPMENT',
    THE_WORKER_HIMSELF = 'THE_WORKER_HIMSELF',
    WAY_AND_SPEED_PERFORMING_WORK_OPERATIONS = 'WAY_AND_SPEED_PERFORMING_WORK_OPERATIONS',
    INJURIES_AND_ACCIDENTS_THAT_HAVE_OCCURRED = 'INJURIES_AND_ACCIDENTS_THAT_HAVE_OCCURRED',
    MANAGEMENT = 'MANAGEMENT',
    PERSON_IN_CHARGE_OF_SAFETY_AT_WORK = 'PERSON_IN_CHARGE_OF_SAFETY_AT_WORK',
}
