export enum Industry {
    CONSTRUCTION = 'CONSTRUCTION',
    AGRICULTURE = 'AGRICULTURE',
    MINING = 'MINING',
    TRANSPORT_AND_LOGISTICS = 'TRANSPORT_AND_LOGISTICS',
    MANUFACTURING = 'MANUFACTURING',
}