export enum Qualification {
    FACULTY_DEGREE = 'FACULTY_DEGREE',
    HIGH_SCHOOL = 'HIGH_SCHOOL',
    PROFESSIONAL_QUALIFICATION = 'PROFESSIONAL_QUALIFICATION',
    SEMI_QUALIFIED_WORKER = 'SEMI_QUALIFIED_WORKER',
    WITHOUT_PROFESSIONAL_QUALIFICATION = 'WITHOUT_PROFESSIONAL_QUALIFICATION',
}
